### ISSUE TITLE
Millisecond interpolation of coordinates

### ISSUE THREAD

**Issue by radiodario** [bakercp/ofxSatellite#1]
Hi there, Thank you so much for this library.

I'm porting a processing version of a visualisation of the orbital debris left behind by the FENGYUN satellite's destruction, and I am using your library. However, i'm realising that the coordinates returned only change once every second. My java implementation uses [the java sgp4 library](https://github.com/shupp/sgp4) which returns positions with a greater degree of interpolation. 

 At the moment, the position / geodetic coords are only changing once a second, rather than increasing smoothly. Since these are high speed objects, the changes are quite abrupt, and occur only once a second.

Is there a way to use milliseconds rather than seconds for the calculations? Or is it a limitation of the c++ implementation of the sgp library? Would it be a better idea to interpolate manually?

Thanks a lot!

Dario

**Comment by bakercp** [comment]
Hey there -- glad you found the addon!

I figured it out!  There was a conversion problem from Poco::DateTime to the satellite's internal date-time that didn't account for milliseconds.

**Comment by radiodario** [comment]
oh wow that was quick man. thank you so much, I also thought there might have been something up with that bit of the conversion, but I wasn't sure.

**Comment by bakercp** [comment]
Cool!  I'd love to see what you're doing with it if you have a link.

Good luck!

**Comment by radiodario** [comment]
here's the Processing version
https://github.com/radiodario/spaceJunk

and the new oF version, which is basically a copy of your satellite tracker example but using a mesh because there are so many points. I'm also updating the points on the update loop rather than draw.
https://github.com/radiodario/orbitalDebris/tree/master

(it's still WIP, need to add GUI and time warp etc)

Thanks again for the library!

**Comment by bakercp** [comment]
Cool stuff.  Once you get it finished up, please feel free to send a PR to this addon repo with links to your project in the readme or any examples you think would help others.  Cheers!

**Comment by radiodario** [comment]
Gotcha! thanks a lot

On Thu, Apr 23, 2015 at 5:33 PM, Christopher Baker <notifications@github.com
