### ISSUE TITLE
cannot compile example 

### ISSUE THREAD

**Issue by icq4ever** [bakercp/ofxSatellite#3]
```
Compiling example_passpredict for Release
make[1]: Entering directory '/home/icq4ever/oF/addons/ofxSatellite/example_passpredict'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal libcurl glfw3 rtaudio libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
with PKG_CONFIG_LIBDIR=
/home/icq4ever/oF/libs/openFrameworksCompiled/project/makefileCommon/config.addons.mk:210: *** missing separator.  Stop.
make[1]: Leaving directory '/home/icq4ever/oF/addons/ofxSatellite/example_passpredict'
make: *** [/home/icq4ever/oF/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2
```

with above error, cannot build.

empty projects are compile/run well without any issue.

environment : arch linux(manjaro distro),  oF010(stable from oF website)

**Comment by bakercp** [comment]
Did you use the develop branch of ofxSatellite?  The master branch is not currently in sync with the stable branch of OF.  Develop should be closer ...

**Comment by icq4ever** [comment]
@bakercp yeah. OF (from github) master branch are working.

ofxSatellite master branch is working. but easycam camera settings needs fix.
ofxSatellite  develop branch is not working with OF master  branch (error: undefined reference to 'Poco::DateTime::DateTime()'). probably other dependencies addon related issue?)

thanks!
